### ISSUE TITLE
Not able to get this working

### ISSUE THREAD

**Issue by ChickenDipper1** [CloudTheWolf/CloudTheWolf.FiveM.Service#1]
Hello,

After following the instructions and running install.bat the error:

"The service is not responding to the control function"

The created service then shows in task manager > services, but will not start. It does not show at all in the services management console.

Please can you help as this would be very handy as a service.

Thanks.

**Comment by CloudTheWolf** [comment]
What happens when you run CloudTheWolf.FiveM.Service.exe directly?

**Comment by ChickenDipper1** [comment]
Thanks for the response, I actually got this working a short while ago.
It needed .net 6.0 to run, great work by the way works perfectly!
